name: Lint

on:
  push:
    branches: [main, "feature/spatial"]
  pull_request:
    branches: [main, "feature/spatial"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
      - name: Install dependencies (dev)
        run: |
          python -m pip install --upgrade pip wheel uv
          python -m uv pip install --system .[dev]
      - name: Run pre-commit on all files
        run: pre-commit run --all-files --show-diff-on-failure
